### ISSUE TITLE
uniqueness point index有誤

### ISSUE THREAD

**Issue by tingwei628** [stanleyexp/uniquep#11]
比較 法文
```
       AssertionError: 
         test: => ak§tRaRjo,3
         assert: => ak§tRaRjo,5
         
       assert 3 == 4
```
```
       AssertionError: 
         test: => abese,3
         assert: => abese,5
         
      assert 3 == 4
```
